# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra',
            field=models.IntegerField(default=0),
        ),
    ]
