# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0003_userprofile_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
