# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0005_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
